export const initialConsoleLines: string[] = [
  "[14:22:01 INFO]: Starting minecraft server version 1.21.1",
  "[14:22:01 INFO]: Loading properties",
  "[14:22:01 INFO]: Default game type: SURVIVAL",
  "[14:22:02 INFO]: Generating keypair",
  "[14:22:02 INFO]: Starting Minecraft server on *:25565",
  "[14:22:02 INFO]: Using epoll channel type",
  "[14:22:03 INFO]: Preparing level \"world\"",
  "[14:22:06 INFO]: Preparing start region for dimension minecraft:overworld",
  "[14:22:09 INFO]: Time elapsed: 3021 ms",
  "[14:22:09 INFO]: Done (7.842s)! For help, type \"help\"",
  "[14:22:10 INFO]: [EssentialsX] Enabling EssentialsX v2.20.1",
  "[14:22:10 INFO]: [LuckPerms] Enabling LuckPerms v5.4.128",
  "[14:22:11 INFO]: [WorldEdit] Enabling WorldEdit v7.3.6",
  "[14:31:44 INFO]: Kestrel_ joined the game",
  "[14:33:02 INFO]: wildberry_pie joined the game",
  "[14:41:18 INFO]: GraniteFox joined the game",
  "[14:52:07 INFO]: Kestrel_ issued server command: /gamemode creative",
  "[15:03:44 INFO]: thundersnap99 joined the game",
  "[15:14:29 INFO]: MossAndMortar fell from a high place",
  "[15:22:00 INFO]: Saved the game",
];

export const consoleLineGenerators: string[] = [
  "[{time} INFO]: {player} joined the game",
  "[{time} INFO]: {player} left the game",
  "[{time} INFO]: {player} lost connection: Disconnected",
  "[{time} INFO]: <{player}> anyone want to trade emeralds?",
  "[{time} INFO]: {player} was slain by Zombie",
  "[{time} INFO]: {player} drowned",
  "[{time} INFO]: {player} issued server command: /spawn",
  "[{time} INFO]: {player} advanced to the title [Diamonds!]",
  "[{time} INFO]: Saved the game",
  "[{time} INFO]: Can't keep up! Is the server overloaded? Running 62ms behind, skipping 1 tick(s)",
];

export const mockPlayerNames = [
  "Kestrel_",
  "wildberry_pie",
  "GraniteFox",
  "thundersnap99",
  "MossAndMortar",
  "quietloom",
  "Basalt_Hollow",
  "emberwick",
  "Null_Pixel",
  "Rowan_Ashcroft",
];
